### PR TITLE
Switch to CMake

### PR DESCRIPTION
**Pull request by OndrejMarsalek**
This is an initial build using CMake. Some options are still missing but should be easy to add. Autools are gone, I feel better already.

I would also follow the lead of Faunus and just bundle XDR: https://github.com/mlund/faunus/tree/master/src/xdrfile

### CODE REVIEW

**Comment by OndrejMarsalek** [comment]
I added the `OPTSURF` option to match the README, but I can't actually find any mention of it in the code.

**Comment by OndrejMarsalek** [comment]
We should find a nice way to set the default value of `CMAKE_BUILD_TYPE` to `Release`.

**Review by fuulish — CHANGES_REQUESTED** [review]
OPTSURF is obsolete, the routine that is used currently was the "optsurf" routine at some point for testing purposes, but has become the default. You can remove that from the README

I think it make sense to keep the bare minimum of autotools files (configure, Makefile.am) so that the poor souls without cmake have a chance of building it. Configure script and similar can be kicked though.

**Comment by OndrejMarsalek** [comment]
I think the poor souls without cmake would be better off just installing it 😉 But, of course, if you want, add back the bits that you find important/relevant. I can't say I know the difference.

**Comment by fuulish** [comment]
I added FindGSL to cmake, an install dir, and include the xdrfile code directly in the code. The latter is licensed under the 2-clause BSD license, which to my understanding is compatible with GPLv3, and I preserved their copyright notice in the respective files. Opinions?

We still need support for einspline and nlopt. We could piggyback on pkg-config as described here:

https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Piggybacking_on_pkg-config

That seems like the easiest solution for now.

**Review by fuulish — APPROVED** [review]

**Comment by OndrejMarsalek** [comment]
My CMake does not know how to find GSL. Should it?

```
Make Warning at CMakeLists.txt:13 (find_package):
  By not providing "FindGSL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GSL", but
  CMake did not find one.

  Could not find a package configuration file provided by "GSL" with any of
  the following names:

    GSLConfig.cmake
    gsl-config.cmake

  Add the installation prefix of "GSL" to CMAKE_PREFIX_PATH or set "GSL_DIR"
  to a directory containing one of the above files.  If "GSL" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by OndrejMarsalek** [comment]
Maybe all optional packages/features can be on by default, so that if they are found, they are just used and the user does not have to do anything?

**Comment by OndrejMarsalek** [comment]
I like the pkg-config mechanism, but would like to use it for GSL as well, unless you forgot to commit FindGSL.

**Comment by fuulish** [comment]
FindGSL should hopefully be available. I tested it on a Debian testing and an OpenSUSE Leap 42.1 machine where it is available in the system path. For reference: https://cmake.org/cmake/help/v3.2/module/FindGSL.html

I would hence refrain from using pkg-config for GSL.

**Comment by fuulish** [comment]
I am a bit unhappy with the behavior of the optional packages when they get activated by the user, but the packages are not found. In our current configuration, cmake will then just go on happily building surf without the optional packages enabled, without any warning/note whatsoever. But, as a user you are fooled into thinking that the features were actually build in until you try to use it, because the build goes smoothly.
I'd rather have the build fail if it doesn't find a feature I requested. That is why I also turned off einspline and nlopt support by default. We can include it in the optional package search. But I think we should make sure that a build fails if a feature was explicitly requested, but couldn't be fulfilled.

**Comment by OndrejMarsalek** [comment]
I see, then we might need to bump the minimum CMake version. My CMake 2.8.12.2 (up-to-date Ubuntu LTS) does not have it.

**Comment by OndrejMarsalek** [comment]
I agree that we should fail if an explicitly requested package is not found. I don't know what the CMake idiom for that is, but I hope there is one.

**Comment by fuulish** [comment]
One can ask for the module to be REQUIRED. But then one would have to do the package find twice for optional package that could be included if they're found. Something like this:

find_package(OpenMP)
option(ENABLE_OPENMP "Use OpenMP parallelization" ON)

if (ENABLE_OPENMP)
  find_package(OpenMP, REQUIRED)
endif()

That would be my quick'n'dirty solution. Or add an else clause that manually breaks/exits if the package is not found:

find_package(OpenMP)
option(ENABLE_OPENMP "Use OpenMP parallelization" OFF)

if (ENABLE_OPENMP AND NOT OPENMP_FOUND)
  \# break
elseif(OPENMP_FOUND)
  option(ENABLE_OPENMP "Use OpenMP parallelization" ON)
  \# do stuff
endif()

**Comment by OndrejMarsalek** [comment]
Hmm, I think this still clashes with the default ON (i.e. you're making it REQUIRED all the time). If you make the default OFF, you're not allowing the user to disable the feature :-/

**Comment by fuulish** [comment]
You're right. I updated the comment. I am not really happy with it, too fiddly, but I think it should work.

**Comment by OndrejMarsalek** [comment]
You could have separate options to allow or require a given feature, but it does not seem very elegant.

**Comment by fuulish** [comment]
I don't like that either. A more complete version:

option(ENABLE_OPENMP "Use OpenMP parallelization" OFF)
find_package(OpenMP)
if(ENABLE_OPENMP AND NOT OPENMP_FOUND)
  MESSAGE(FATAL_ERROR "Could not find OPENMP.")
elseif(OPENMP_FOUND)
  set(ENABLE_OPENMP ON CACHE BOOL "Use OpenMP parallelization")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  add_definitions(-DOPENMP)
endif()

It doesn't work the way I want it to. If it finds openmp and by default the option is set to off, the configure step should enter the elseif() statement (and it does). But, it doesn't set ENABLE_OPENMP to ON, and neither does it add -fopenmp to the compiler flags. It sets the -DOPENMP preprocessor flag, though.

Any suggestions for this specific version?

**Comment by OndrejMarsalek** [comment]
Best I could find is the following for the with/without idiom. I think if one wants to have this kind of flexibility, this is the only clean way.

http://stackoverflow.com/questions/7103808/how-to-configure-in-cmake#7103859

Otherwise just respect the ENABLE option (with whatever default you decide) and make it REQUIRED.

**Comment by OndrejMarsalek** [comment]
What I mean is EDIT 1 and EDIT 2 of the original question.

**Comment by fuulish** [comment]
I like it, so could we agree on this:

option(ENABLE_OPENMP "Use OpenMP parallelization" OFF)
option(DISABLE_OPENMP "Disable OpenMP parallelization" OFF)

if (ENABLE_OPENMP)
    find_package(OpenMP REQUIRED)
elseif(NOT DISABLE_OPENMP)
    find_package(OpenMP)
endif(ENABLE_OPENMP)

if (NOT DISABLE_OPENMP AND OPENMP_FOUND)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    add_definitions(-DOPENMP)
endif()

??? I would do the corresponding changes for the options (maybe even use a macro :)

**Comment by fuulish** [comment]
With the last changes just pushed, I would be happy to merge it into master.

**Comment by OndrejMarsalek** [comment]
Nice, I like it! Is the manual manipulation of `CMAKE_C_FLAGS` really needed? I would hope not.

**Comment by fuulish** [comment]
I don't know, I took that from your initial version, AFAICR.

**Comment by fuulish** [comment]
It builds fine without it, and all the variables are actually empty. Removed it.

**Comment by OndrejMarsalek** [comment]
So, use `find_optional_package` for nlopt and einspline as well and merge?

**Comment by fuulish** [comment]
That was my original thought. Somehow my modifications to the macro did not work out. I'll try later again and commit/merge if it works.

**Comment by fuulish** [comment]
Done, and done.

**Comment by OndrejMarsalek** [comment]
Sweet :-) Thanks, this is now much more pleasant to build and use.

**Pull request merged**
